server:
  port: 7996
  servlet:
    context-path: /ribbon

spring:
  application:
      name: microservice-consumer-movie-ribbon-with-hystrix2

eureka:
  client:
    healthcheck:
      enabled: true #默认是false，EurekaDiscoveryClientConfiguration;前提加actuator依赖
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    home-page-url-path: /ribbon

management:
  endpoints:
    web:
      exposure:
       include: "*"
  endpoint:
    health:
      show-details: always