server:
  port: 7996

spring:
  application:
      name: microservice-consumer-movie-feign-with-hystrix-factory

eureka:
  client:
    healthcheck:
      enabled: true #默认是false，EurekaDiscoveryClientConfiguration;前提加actuator依赖
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka

logging:
  level:
    root: debug

management:
  endpoints:
    web:
      exposure:
       include: "*"
  endpoint:
    health:
      show-details: always

feign:
  hystrix:
    enabled: true