server:
  port: 7997
  servlet:
    context-path: /ribbon
spring:
  application:
      name: microservice-consumer-movie-ribbon-with-hystrix3
eureka:
  client:
    healthcheck:
      enabled: true #默认是false，EurekaDiscoveryClientConfiguration;前提加actuator依赖
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    home-page-url-path: /ribbon
    metadata-map:
      management.port: ${management.port:7987}


management:
  endpoints:
    web:
      exposure:
       include: "*"
  endpoint:
    health:
      show-details: always
  server:
    port: 7987 #spring-boot-actuator