server:
  port: 8100
spring:
  application:
    name: microservice-sidecar
eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
       include: "*"  # * 在yaml 文件属于关键字，所以需要加引号；开启actuator其它接口

sidecar:
  #node-service
  port: 8060
  health-uri: http://localhost:8060/health.json
