spring:
  application:
    name: wallet-service  # the same with com.yiqiniu.easytrans.demos.order.Constant.APPID
  datasource: # order service datasource config
    url: jdbc:mysql://localhost:3306/wallet?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

server:
  port: 8081

logging:
  level:
    root: debug
 
# RIBBON用，也可以直接开启Eureka
#order-service:
#  ribbon:
#    listOfServers: localhost:8080
#
#wallet-service:
#  ribbon:
#    listOfServers: localhost:8081

easytrans:
  master:
    zk:
      zooKeeperUrl: 193.112.79.100:2181
  stringcodec:
    zk:
      zooKeeperUrl: ${easytrans.master.zk.zooKeeperUrl}
  idgen:
    trxId:
      zkSnow:
        zooKeeperUrl: ${easytrans.master.zk.zooKeeperUrl}
  log:
    database:
      logCleanEnabled: true
      logReservedDays: 14
      logCleanTime: 01:22:00
      druid:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/wallet_translog?characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456




    
      