server:
  port: 7992

spring:
  application:
      name: microservice-consumer-movie-ribbon-without-eureka

eureka:
  client:
    healthcheck:
      enabled: true #默认是false，EurekaDiscoveryClientConfiguration;前提加actuator依赖
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka

ribbon:
  eureka:
   enabled: false

microservice-provider-user:
  ribbon:
    listOfServers: localhost:7900