server:
  port: 7994

spring:
  application:
      name: microservice-consumer-movie-ribbon-with-hystrix

eureka:
  client:
    healthcheck:
      enabled: true #默认是false，EurekaDiscoveryClientConfiguration;前提加actuator依赖
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
       include: "*"  # * 在yaml 文件属于关键字，所以需要加引号；开启actuator其它接口