server:
  port: 7900
spring:
  application:
    name: redis-lock-test1
  redis:
# Redis数据库索引（默认为0）
    database: 0
# Redis服务器地址 （默认为127.0.0.1）
    host: 192.168.123.118
# Redis服务器连接端口 （默认为6379）
    port: 6379
# Redis服务器连接密码（默认为空）
    password:
# 连接超时时间（毫秒）
    timeout: 2000
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
